server:
  context-path: /oauth2-service
  port: 8081

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: oauth2
#      username:
#      password:
  mvc:
    async:
      request-timeout: 300000 # 5 mins
  jackson:
    property-naming-strategy: SNAKE_CASE
